package dev.dexuby.minecraftplugin.property;

public enum Property {

    JDK,
    JDK_TYPE,
    PROJECT_NAME,
    VERSION,
    AUTHOR,
    GROUP_ID,
    ARTIFACT_ID,
    ARTIFACT_ID_SAFE,
    SERVER_VERSION_PLUGIN_TARGET,
    SERVER_VERSION_GROUP_ID,
    SERVER_VERSION_ARTIFACT_ID,
    SERVER_VERSION_VERSION,
    SERVER_VERSION_REPO_ID,
    SERVER_VERSION_REPO_URL

}
